.\"
.\" Copyright (c) 2021-2022 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 23, 2021
.Dt BSDDIALOG 1
.Os
.Sh NAME
.Nm bsddialog
.Nd TUI dialogs
.Sh SYNOPSIS
.Nm
.Fl Fl help
.Nm
.Fl Fl version
.Nm
.Op Fl Fl common-opts
.Fl Fl dialog
.Ar text
.Ar rows
.Ar cols
.Op Ar dialog-opts
.Sh DESCRIPTION
The
.Nm bsddialog
utility build build Text User Interface dialogs and widgets: to display
messages, to get input and to inform about a computation status.
.Pp
.Ar rows
and
.Ar cols
are the height and width of the dialog, 0 for autosize and -1 for fullscreen.
.Ar text
is a message printed inside the dialog, except for
.Fl Fl textbox
described later. The user input got by the dialogs is printed to the standard
error.
.Ss Common options
The following options are common to some dialog and can change the default
behavior of the utility:
.Bl -tag -width Ds
.It Fl Fl ascii-lines
Ascii characters to draw lines.
.It Fl Fl backtitle Ar backtitle
Print a title on the top side of the screen.
.It Fl Fl begin-x Ar x
Dialog horizontal position, 0 is the left screen size, default center.
.It Fl Fl begin-y Ar y
Dialog vertical position, 0 is the top screen side, default center.
.It Fl Fl cancel-label Ar string
Label for the Cancel button.
.It Fl Fl clear
Hide the Dialog at exit.
.It Fl Fl colors
Enable highlights for text, the following sequences are considered escapes:
.Bl -column -compact
.It Dq \eZ0
black.
.It Dq \eZ1
red.
.It Dq \eZ2
green.
.It Dq \eZ3
yellow.
.It Dq \eZ4
blue.
.It Dq \eZ5
magenta.
.It Dq \eZ6
cyan.
.It Dq \eZ7
white.
.It Dq \eZr
reverse foreground and background colors.
.It Dq \eZR
disable reverse.
.It Dq \eZb
bold.
.It Dq \eZB
disable bold.
.It Dq \eZu
underline.
.It Dq \eZU
disable underline.
.It Dq \eZn
restore to normal text.
.El
.It Fl Fl cr-wrap
Replace new line with a space in
.Ar text .
.It Fl Fl date-format Ar format
string accepted by
.Xr strftime 3
to customize the output of
.Fl Fl datebox .
.It Fl Fl defaultno
Focus on Cancel or No button on startup.
.It Fl Fl default-button Ar label
Focus on the button with
.Ar label
on startup.
.It Fl Fl default-no
Equivalent to
.Fl Fl defaultno
.It Fl Fl default-item Ar name
Focus on item with
.Ar name ,
for Checklist, Menu, Radiolist and Treeview.
.It Fl Fl disable-esc
Do not quit the dialog with ESC key.
.It Fl Fl esc-cancelvalue
.Nm bsddialog
exits with Cancel button value, see
.Sx EXIT STATUS .
.It Fl Fl exit-label Ar label
Equivalent to
.Fl Fl ok-label .
.It Fl Fl extra-button
Add a button with Extra label.
.It Fl Fl extra-label Ar label
Set
.Ar label
for the Extra button.
.It Fl Fl generic1-button Ar label
Add a button with
.Ar label .
.It Fl Fl generic2-button Ar label
Add a button with
.Ar label.
.It Fl Fl help
Print this list of options and exit.
.It Fl Fl help-button
Add a button with Help label.
.It Fl Fl help-label Ar label
Set
.Ar label
for Help button.
.It Fl Fl help-status
Print also the selected items if the Help button is pressed.
.It Fl Fl help-tags
Force to print the name of the focused item if the Help button is pressed also
with
.Fl Fl item-help .
.It Fl Fl hfile Ar filename
Open
.Ar filename
in a Textbox if F1 key is pressed,
.It Fl Fl hline Ar string
Dialog subtitle.
.It Fl Fl hmsg Ar string
Open a msgbox with
.Ar string
like its
.Ar text
if the F1 key is pressed.
.It Fl Fl ignore
TODO.
.It Fl Fl insecure
Print '*' to hide passwords while typing, default whitespace.
.It Fl Fl item-depth
Specify a margin for items of Checklist, Menu and Radiolist.
.It Fl Fl item-help
Set a help string for Checklist, Menu, Radiolist and Treeview items to display
at the bottom screen side.
.It Fl Fl item-prefix
Set a margin for each item.
.It Fl Fl max-input Ar size
Maximum length of the input for
.Fl Fl input-box
ans
.Fl Fl passwordbox ,
defalt 2048.
.It Fl Fl no-cancel
.It Fl Fl nocancel
Do not show Cancel button.
.It Fl Fl no-collapse
Do not replace tab with a space in
.Ar text .
.It Fl Fl no-items
Do not display items desciption.
.It Fl Fl no-label Ar label
Equivalent to
.Fl Fl cancel-label Ar label
.It Fl Fl no-lines
Do not draw borders and lines.
.It Fl Fl no-nl-expand
do not consider the sequence
.Dq \n
like new line.
.It Fl Fl no-ok
.It Fl Fl nook
Do not draw OK button, alike EXIT and Yes.
.It Fl Fl no-shadow
Disable pseudo dialog shadow.
.It Fl Fl no-tags
Do not display items name.
.It Fl Fl ok-label Ar label
Set
.Ar label
for OK button.
.It Fl Fl output-fd Ar fd
Output to the specified file descriptor.
.It Fl Fl output-separator Ar sep
Set a sepator for the items in output, default whitespace.
.It Fl Fl print-maxsize
Screen size.
.It Fl Fl print-size
Print Dialog height and widget at exit.
.It Fl Fl print-version
Print
.Nm bsddialog
version and exit.
.It Fl Fl quoted
Quote items in output, default only when necessary.
.It Fl Fl separate-output
Separate selected items with a new line.
.It Fl Fl separator Ar sep
Equivalent to
.Fl Fl output-separator .
.It Fl Fl shadow
Show a pseudo shadow for the dialog, enabled by default.
.It Fl Fl single-quoted
Use sinnque quote for items in output.
.It Fl Fl sleep Ar secs
Wait
.Ar secs
seconds to close the dialog.
.It Fl Fl stderr
Output to standand error,
.Nm bsddialog
default.
.It Fl Fl stdout
Output to standard output.
.It Fl Fl tab-len Ar spaces
White spaces to print a tab.
.It Fl Fl theme Ar blackwhite|bsddialog|default|dialog
Set a theme.
.It Fl Fl time-format Ar format
TODO.
.It Fl Fl title Ar title
Dialog title.
.It Fl Fl trim
TODO.
.It Fl Fl version
TODO.
.It Fl Fl yes-label Ar label
Equivalent to
.Fl Fl ok-label .
.El
.Ss Dialogs
The following dialogs are available:
.Bl -tag -width Ds
.It Fl Fl checklist Ar text Ar rows Ar cols Ar menurows Oo Ar name Ar desc \
Ar status Oc ...
Checklist to select some item from a list via the SPACE key, each item has a
.Ar name ,
.Ar desc
and a default
.Ar status
specified by
.Dq on
or
.Dq off .
The names of the selected items are printed in the standard error.
.Ar menurows
is the graphical height of the list.
.It Fl Fl datebox Ar text Ar rows Ar cols Op Ar year Ar month Ar day
Dialog to select a date.
.It Fl Fl form Ar text Ar rows Ar cols Ar formrows Oo Ar label Ar ylabel \
Ar xlabel Ar init Ar yfield Ar xfield Ar fieldlen Ar valuelen Oc ...
Dialog to get strings in input, 
.It Fl Fl gauge Ar text Ar rows Ar cols Op Ar perc
TODO.
.It Fl Fl infobox Ar text Ar rows Ar cols
Dialog without buttons to display a message and to exit immediately.
.It Fl Fl inputbox Ar text Ar rows Ar cols Op Ar init
Dialog to get a string in input and to print it in the standard error.
.Ar init
is the default value.
.It Fl Fl menu Ar text Ar rows Ar cols Ar menurows Oo Ar name desc Oc ...
builds a menu to select an item from a list, each item has a
.Ar name
and a 
.Ar desc .
The names of the selected item is printed in the standard error.
.Ar menurows
is the graphical height of the list.
.It Fl Fl mixedform Ar text Ar rows Ar cols Ar formrows Oo Ar label Ar ylabel \
Ar xlabel Ar init Ar yfield Ar xfield Ar fieldlen Ar valuelen Ar flag Oc ...
TODO.
.It Fl Fl mixedgauge Ar text Ar rows Ar cols Ar mainperc Oo Ar minilabel \
Ar miniperc Oc ...
Dialog to show a main bar to represent
.Ar mainperc
from 0 to 100 and some mini bar with a
.Ar minilabel
string and a
.Ar miniperc
with value from 0 and 100 or negative value prints a descriptive string: -1
.Dq Succeeded ,
-2
.Dq Failed ,
-3
.Dq Passed ,
-4
.Dq Completed ,
-5
.Dq Checked ,
-6
.Dq Done ,
-7
.Dq Skipped ,
-8
.Dq \&In Progress ,
-9
blank line
-10
.Dq N/A ,
-11
.Dq Pending .
.It Fl Fl msgbox Ar text Ar rows Ar cols
Dialog to diplay a message without the Cancel button.
.It Fl Fl passwordbox Ar text Ar rows Ar cols Op Ar init
Dialog to get a password and prints it in the standard error,
.Ar init
is the default value.
.It Fl Fl passwordform Ar text Ar rows Ar cols Ar formrows Oo Ar label \
Ar ylabel Ar xlabel Ar init Ar yfield Ar xfield  Ar fieldlen Ar valuelen Oc ...
Dialog to get a list of passwords in input.
.It Fl Fl pause Ar text Ar rows Ar cols Ar seconds
Dialog runs until the timeout in
.Ar seconds
expires or a button is pressed.
.It Fl Fl radiolist Ar text Ar rows Ar cols Ar menurows Oo Ar name Ar desc \
Ar status Oc ...
Builds a radiolist to select an item from a list via the SPACE key, each item
has a
.Ar name ,
.Ar desc
and a default
.Ar status
specified by
.Dq on
or
.Dq off .
The names of the selected item is printed in the standard error.
.Ar menurows
is the graphical height of the list.
.It Fl Fl rangebox Ar text Ar rows Ar cols Ar min Ar max Op Ar init
Dialog to select a value between
.Ar min
and
.Ar max ,
.Ar init
is the default value, the keys UP, DOWN, HOME, END, PAGEUP and PAGEDOWN can
change it.
The selected value is printed in the standard error.
.It Fl Fl textbox Ar file Ar rows Ar cols
opens and prints
.Ar file
the UP, DOWN, HOME, END, PAGEUP and PAGEDOWN keys are availble to navigate
the file.
OK button is renamed EXIT.
.It Fl Fl timebox Ar text Ar rows Ar cols Op Ar hour Ar min Ar sec
Dialog to select a time.
.It Fl Fl treeview Ar text Ar rows Ar cols Ar menurows Oo Ar depth Ar name \
Ar desc Ar status Oc ...
Equivalent to Radiolist with
.Fl Fl  item-depth
and
.Fl Fl no-name .
.It Fl Fl yesno Ar text Ar rows Ar cols
.Dq Yes-No Question ,
the OK and Cancel buttons are renamed Yes and No.
.El
.Sh EXIT STATUS
The
.Nm
utility exits 255 on unsuccessful, otherwise depending on the button or key
pressed the following values can be returned:
.Bl -column -compact
.It 0
OK or Yes button.
.It 1
Cancel or No button.
.It 2
Help button.
.It 3
Extra button.
.It 4
Timeout.
.It 5
ESC key.
.It 6
Generic 1 button.
.It 7
Generic 2 button.
.Ed
.Sh EXAMPLES
Backtitle, title and message:
.Dl bsddialog --backtitle INFO --title info --msgbox Message 0 0
.Pp
Yes-No Question and theme:
.Dl bsddialog --theme blackwhite --yesno Question 10 30
.Pp
Checklist:
.Dl bsddialog --checklist Checklist 0 0 3 N1 \&D1 off N2 D2 on N3 D3 off
.Pp
Gauge:
.Bd -literal -offset indent -compact
i=1
for c in A B C D E F G H
do
	sleep 1
	echo XXX
	echo "$(expr $(expr $i "*" 100) "/" 8)"
	echo "[$i/8] Char: $c"
	echo XXX
	if [ $i -eq 8 ]
	then
		echo EOF
	fi
	i=`expr $i + 1`
done | bsddialog --title " gauge " --gauge "Starting..." 10 70
.Ed
.Sh SEE ALSO
.Xr bsddialog 3 .
.Sh HISTORY
The
.Nm bsddialog
utility first appeared in
.Fx 14.0 .
.Sh AUTHORS
.Nm bsddialog
was written by
.An Alfonso Sabato Siciliano Aq Mt alf.siciliano@gmail.com .
.Sh BUGS
The forms do not resize the dialog after a terminal change and does not provides
scrolling for items.