.\"
.\" Copyright (c) 2021 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd April 14, 2021
.Dt BSDDIALOG 3
.Os
.Sh NAME
.Nm bsddialog_buildlist ,
.Nm bsddialog_calendar ,
.Nm bsddialog_checklist ,
.Nm bsddialog_dselect ,
.Nm bsddialog_editbox ,
.Nm bsddialog_form ,
.Nm bsddialog_fselect ,
.Nm bsddialog_gauge ,
.Nm bsddialog_infobox ,
.Nm bsddialog_inputbox ,
.Nm bsddialog_inputmenu ,
.Nm bsddialog_menu ,
.Nm bsddialog_mixedform ,
.Nm bsddialog_mixedgauge ,
.Nm bsddialog_msgbox ,
.Nm bsddialog_passwordbox ,
.Nm bsddialog_passwordform ,
.Nm bsddialog_pause ,
.Nm bsddialog_prgbox ,
.Nm bsddialog_programbox ,
.Nm bsddialog_progressbox ,
.Nm bsddialog_radiolist ,
.Nm bsddialog_rangebox ,
.Nm bsddialog_tailbox ,
.Nm bsddialog_tailboxbg ,
.Nm bsddialog_textbox ,
.Nm bsddialog_timebox ,
.Nm bsddialog_treeview ,
.Nm bsddialog_yesno
.Nd library for TUI Widgets
.Sh LIBRARY
.Lb libbsddialog
.Sh SYNOPSIS
.In bsddialog.h
.Ft "int"
.Fn bsddialog_buildlist "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_calendar "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_checklist "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_dselect "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_editbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_form "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_fselect "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_gauge "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_infobox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_inputbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_inputmenu "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_menu "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_mixedform "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_mixedgauge "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_msgbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_passwordbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_passwordform "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_pause "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_prgbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_programbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_progressbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_radiolist "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_rangebox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_tailbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_tailboxbg "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_textbox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_timebox "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_treeview "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Ft "int"
.Fn bsddialog_yesno "struct bsddialog_conf conf" "char *text" "int height" "int width"
.Sh DESCRIPTION
The
.Nm bsddialog
library builds Text User Interface Widgets.
.\" .Sh IMPLEMENTATION NOTES
.\" Not used in OpenBSD.
.Sh RETURN VALUES
.Fd #define BSDDIALOG_YESOK
.Fd #define BSDDIALOG_NOCANCEL
.Fd #define BSDDIALOG_HELP
.Fd #define BSDDIALOG_EXTRA
.Fd #define BSDDIALOG_ITEM_HELP
.Fd #define BSDDIALOG_ERROR
.\" .Sh FILES
.\" .Sh EXAMPLES
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Xr bsddialog 3 ,
.Xr dialog 1 ,
.Xr dialog 3
.Sh HISTORY
The
.Nm bsddialog
library first appeared in
.Fx 14.0 .
.Sh AUTHORS
.Nm bsddialog
was written by
.An Alfonso Sabato Siciliano Aq Mt alf.siciliano@gmail.com .