.\"
.\" Copyright (c) 2021-2022 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 14, 2021
.Dt BSDDIALOG 1
.Os
.Sh NAME
.Nm bsddialog
.Nd TUI dialogs
.Sh SYNOPSIS
.Nm bsddialog
.Fl -help
.Nm bsddialog
.Fl -version
.Nm bsddialog
.Op Fl Ar -common-opts
.Fl Ar -widget
.Fl Ar text
.Fl Ar rows
.Fl Ar cols
.Op Fl Ar -dialog-opts
.Sh DESCRIPTION
The
.Nm bsddialog
utility build build Text User Interface dialogs and widgets: to display
messages, to get input and to inform about a computation status.
.Ss Common options
.Ss Dialogs
.Sh EXIT STATUS
The
.Nm
utility exits -1 or 255, depending by the terminal, on unsuccessful.
Otherwise, depending on the pressed button, key or user input the following
values can be returned:
.Bl -column -compact
.It 0
Ok or Yes button.
.It 1
Cancel or No button.
.It 2
Help button.
.It 3
Extra button.
.It 4
timeout.
.It 5
ESC key.
.\" .It 6
.\" Generic 1 button.
.\" .It 7
.\" Generic 2 button.
.Ed
.Sh EXAMPLES
Backtitle, title and message Example:
.Dl bsddialog --backtitle INFO --title info --msgbox Message 0 0
.Pp
.Dq Yes-No Question
and theme Example:
.Dl bsddialog --theme blackwhite --yesno Question 10 30
.Pp
Checklist Example:
.Dl bsddialog --checklist Checklist 0 0 3 N1 \&D1 off N2 D2 on N3 D3 off
.Pp
Gauge script:
.Pp
.Bd -literal -offset indent -compact
input="A B C D E F G"
total=`echo $input | awk '{print split($0, a)}'`
curr=1
for i in $input
do
	sleep 1
	perc="$(expr $(expr $curr "*" 100 ) "/" $total )"
	echo XXX
	echo $perc
	echo "[$curr/$total] Input: $i"
	echo XXX
	if [ $curr -eq $total ]
	then
		echo EOF
	fi
	curr=`expr $curr + 1`
done | ./bsddialog --title " gauge " --gauge "Starting..." 10 70 0
.Ed
.Sh SEE ALSO
.Xr bsddialog 3 .
.Sh HISTORY
The
.Nm bsddialog
utility first appeared in
.Fx 14.0 .
.Sh AUTHORS
.Nm bsddialog
was written by
.An Alfonso Sabato Siciliano Aq Mt alf.siciliano@gmail.com .
.Sh BUGS
.Fn bsddialog_form
does not resize the dialog after a terminal change and does not provides
scrolling for items.