.\"
.\" Copyright (c) 2021-2022 Alfonso Sabato Siciliano
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd January 14, 2021
.Dt BSDDIALOG 1
.Os
.Sh NAME
.Nm bsddialog
.Nd TUI dialogs
.Sh SYNOPSIS
.Nm bsddialog
.Fl Fl help
.Nm bsddialog
.Fl Fl version
.Nm bsddialog
.Op Fl Fl common-opts
.Fl Fl dialog
.Ar text
.Ar rows
.Ar cols
.Op Fl Fl dialog-opts
.Sh DESCRIPTION
The
.Nm bsddialog
utility build build Text User Interface dialogs and widgets: to display
messages, to get input and to inform about a computation status.
.Ss Common options
.Bl -tag -width Ds
.It Fl Fl ascii-lines
TODO.
.It Fl Fl backtitle Ar backtitle
TODO.
.It Fl Fl begin-x Ar x
TODO.
.It Fl Fl begin-y Ar y
TODO.
.It Fl Fl cancel-label Ar string
TODO.
.It Fl Fl clear
TODO.
.It Fl Fl colors
TODO.
.It Fl Fl cr-wrap
TODO.
.It Fl Fl date-format Ar format
TODO.
.It Fl Fl defaultno
TODO.
.It Fl Fl default-button Ar label
TODO.
.It Fl Fl default-no
TODO.
.It Fl Fl default-item Ar name
TODO.
.It Fl Fl disable-esc
TODO.
.It Fl Fl esc-cancelvalue
TODO.
.It Fl Fl exit-label Ar label
TODO.
.It Fl Fl extra-button
TODO.
.It Fl Fl extra-label Ar label
TODO.
.It Fl Fl generic1-button Ar label
TODO.
.It Fl Fl generic2-button Ar label
TODO.
.It Fl Fl help
TODO.
.It Fl Fl help-button
TODO.
.It Fl Fl help-label Ar label
TODO.
.It Fl Fl help-status
TODO.
.It Fl Fl help-tags
TODO.
.It Fl Fl hfile Ar filename
TODO.
.It Fl Fl hline Ar string
TODO.
.It Fl Fl hmsg Ar string
TODO.
.It Fl Fl ignore
TODO.
.It Fl Fl insecure
TODO.
.It Fl Fl item-depth
TODO.
.It Fl Fl item-help
TODO.
.It Fl Fl items-prefix
TODO.
.It Fl Fl max-input Ar size
TODO.
.It Fl Fl no-cancel
TODO.
.It Fl Fl nocancel
TODO.
.It Fl Fl no-collapse
TODO.
.It Fl Fl no-items
TODO.
.It Fl Fl no-label Ar label
TODO.
.It Fl Fl no-lines
TODO.
.It Fl Fl no-nl-expand
TODO.
.It Fl Fl no-ok
TODO.
.It Fl Fl nook
TODO.
.It Fl Fl no-shadow
TODO.
.It Fl Fl no-tags
TODO.
.It Fl Fl ok-label Ar label
TODO.
.It Fl Fl output-fd Ar fd
TODO.
.It Fl Fl output-separator Ar sep
TODO.
.It Fl Fl print-maxsize
TODO.
.It Fl Fl print-size
TODO.
.It Fl Fl print-version
TODO.
.It Fl Fl quoted
TODO.
.It Fl Fl separate-output
TODO.
.It Fl Fl separator Ar sep
TODO.
.It Fl Fl shadow
TODO.
.It Fl Fl single-quoted
TODO.
.It Fl Fl sleep Ar secs
TODO.
.It Fl Fl stderr
TODO.
.It Fl Fl stdout
TODO.
.It Fl Fl tab-len Ar spaces
TODO.
.It Fl Fl theme Ar blackwhite|bsddialog|dialog
TODO.
.It Fl Fl time-format Ar format
TODO.
.It Fl Fl title Ar title
TODO.
.It Fl Fl trim
TODO.
.It Fl Fl version
TODO.
.It Fl Fl yes-label Ar label
TODO.
.El
.Ss Dialogs
The following dialogs are available:
.Bl -tag -width Ds
.It Fl Fl checklist Ar text Ar rows Ar cols Ar menurows Op Ar name Ar desc Ar status ...
builds a checklist with
.Ar menurows
height.
.It Fl Fl datebox Ar text Ar rows Ar cols Op year month day
TODO.
.It Fl Fl form Ar text Ar rows Ar cols Ar formrows Op Ar label ylabel xlabel init yfield xfield fieldlen maxvalue ...
TODO.
.It Fl Fl gauge Ar text Ar rows Ar cols Op perc
TODO.
.It Fl Fl infobox Ar text Ar rows Ar cols
TODO.
.It Fl Fl inputbox Ar text Ar rows Ar cols Op initstring
TODO.
.It Fl Fl menu Ar text Ar rows Ar cols Ar menurows Op Ar name desc ...
TODO.
.It Fl Fl mixedform Ar text Ar rows Ar cols Ar formrows Op Ar label ylabel xlabel init yfield xfield fieldlen maxvalue 0|1|2 ...
TODO.
.It Fl Fl mixedgauge Ar text Ar rows Ar cols Ar mainperc Op Ar minilabel Ar miniperc ...
TODO  <mainperc> [<minilabel> <-123456789|-10|-11|miniperc> ...].
.It Fl Fl msgbox Ar text Ar rows Ar cols
TODO.
.It Fl Fl passwordbox Ar text Ar rows Ar cols Op Ar defaultvalue
TODO.
.It Fl Fl passwordform Ar text Ar rows Ar cols Ar formrows Op Ar label Ar ylabel Ar xlabel Ar init Ar yfield Ar Ar xfield  Ar fieldlen Ar maxvalue ...
TODO.
.It Fl Fl pause Ar text Ar rows Ar cols Ar seconds
TODO.
.It Fl Fl radiolist Ar text Ar rows Ar cols Ar menurows Op Ar name Ar desc Ar on|off ...
TODO.
.It Fl Fl rangebox Ar text Ar rows Ar cols Ar min Ar max Op Ar default
TODO.
.It Fl Fl textbox Ar file Ar rows Ar cols
TODO.
.It Fl Fl timebox Ar text Ar rows Ar cols Op Ar hour Ar min Ar sec
TODO.
.It Fl Fl treeview Ar text Ar rows Ar cols Ar menurows Op Ar depth Ar name Ar desc Ar on|off ...
TODO
.It Fl .yesno Ar text Ar rows Ar cols
TODO.
.El
.Sh EXIT STATUS
The
.Nm
utility exits -1 or 255, depending by the terminal, on unsuccessful.
Otherwise, depending on the pressed button, key or user input the following
values can be returned:
.Bl -column -compact
.It 0
Ok or Yes button.
.It 1
Cancel or No button.
.It 2
Help button.
.It 3
Extra button.
.It 4
Timeout.
.It 5
ESC key.
.It 6
Generic 1 button.
.It 7
Generic 2 button.
.Ed
.Sh EXAMPLES
Backtitle, title and message:
.Dl bsddialog --backtitle INFO --title info --msgbox Message 0 0
.Pp
.Dq Yes-No Question
and theme:
.Dl bsddialog --theme blackwhite --yesno Question 10 30
.Pp
Checklist:
.Dl bsddialog --checklist Checklist 0 0 3 N1 \&D1 off N2 D2 on N3 D3 off
.Pp
Gauge:
.Bd -literal -offset indent -compact
i=1
for c in A B C D E F G H
do
	sleep 1
	echo XXX
	echo "$(expr $(expr $i "*" 100) "/" 8)"
	echo "[$i/8] Char: $c"
	echo XXX
	if [ $i -eq 8 ]
	then
		echo EOF
	fi
	i=`expr $i + 1`
done | bsddialog --title " gauge " --gauge "Starting..." 10 70
.Ed
.Sh SEE ALSO
.Xr bsddialog 3 .
.Sh HISTORY
The
.Nm bsddialog
utility first appeared in
.Fx 14.0 .
.Sh AUTHORS
.Nm bsddialog
was written by
.An Alfonso Sabato Siciliano Aq Mt alf.siciliano@gmail.com .
.Sh BUGS
The forms do not resize the dialog after a terminal change and does not provides
scrolling for items.