# PUBLIC DOMAIN - NO WARRANTY, see:
# 	<http://creativecommons.org/publicdomain/zero/1.0/>
#
# Written by Alfonso Sabato Siciliano

CFLAGS = -Wall -g
INCLUDEDIR = ./
LDFLAGS = -lform -lncurses -ltinfo
OUTPUT = bsddialog
HEADERS = bsddialog.h theme.h
SOURCES = theme.c menus.c lib_util.c libbsddialog.c bsddialog.c
OBJECTS = $(SOURCES:.c=.o)
RM = rm -f

all : $(OUTPUT)

clean:
	$(RM) $(OUTPUT) *.o *~

$(OUTPUT): $(OBJECTS)
	$(CC) $^ -o $@ $(LDFLAGS)

%.o: %.c $(HEADERS)
	$(CC) $(CFLAGS) -I$(INCLUDEDIR) -c $<
