#!/bin/sh

libpath=../lib
examples="buildlist menu treeview checklist radiolist dialog4ports theme \
	infobox yesno msgbox"

for e in $examples
do
	cc -Wall -I$libpath ${e}.c -o $e -L$libpath -lbsddialog -Wl,-rpath=$libpath
done
