#!/bin/sh

lib="../theme.c ../lib_util.c ../menus.c ../libbsddialog.c"
examples="buildlist menu treeview checklist radiolist dialog4ports theme \
	infobox yesno msgbox"

for e in $examples
do
	cc -Wall $lib ${e}.c -o $e -lform -lncurses
done
