#!/bin/sh

libpath=../lib
examples="menu treeview checklist radiolist mixedlist theme \
	infobox yesno msgbox datebox form timebox rangebox pause"

for e in $examples
do
	cc -g -Wall -I$libpath ${e}.c -o $e -L$libpath -lbsddialog -Wl,-rpath=$libpath
done
